# Generated by Django 5.0.6 on 2024-06-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='add_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
