# Generated by Django 5.0.6 on 2024-06-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_add_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loyalty',
        ),
    ]
