# Generated by Django 5.0.6 on 2024-06-06 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('installed', 'Installed')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_pdf', models.FileField(upload_to='check/')),
                ('address', models.CharField(max_length=250)),
                ('contract_pdf', models.FileField(upload_to='contracts/')),
                ('specification_pdf', models.FileField(upload_to='specifications/')),
                ('model_3d', models.FileField(upload_to='3d_models/')),
                ('order_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('installation_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
