# Generated by Django 5.0.6 on 2024-06-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images/image/')),
                ('design', models.ImageField(upload_to='product_images/design/')),
                ('model_3d', models.FileField(upload_to='product_models/')),
                ('category', models.CharField(max_length=50)),
                ('purpose', models.CharField(choices=[('home', 'Домой'), ('office', 'В офис'), ('kids', 'Детская')], default='home', max_length=10)),
                ('shape', models.CharField(max_length=100)),
                ('facade_material', models.CharField(max_length=100)),
                ('countertop_material', models.CharField(max_length=100)),
            ],
        ),
    ]
