# Generated by Django 5.0.6 on 2024-06-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kitchen', 'Кухня'), ('wardrobe', 'Гардероб'), ('hallway', 'Прихожая'), ('dresser', 'Комод'), ('rack', 'Стеллаж')], default='kitchen', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='countertop_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал столешницы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.ImageField(blank=True, upload_to='product_images/design/', verbose_name='ЧБ эскиз'),
        ),
        migrations.AlterField(
            model_name='product',
            name='facade_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал фасадов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, upload_to='product_models/', verbose_name='3д модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purpose',
            field=models.CharField(choices=[('home', 'Домой'), ('office', 'В офис'), ('kids', 'Детская')], default='home', max_length=10, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(blank=True, max_length=100, verbose_name='Форма изделия'),
        ),
    ]
