# Generated by Django 4.2.13 on 2024-06-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=200, verbose_name='Размеры (ШхВхГ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Наполнение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='product_images/image/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='product_images/image/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_time',
            field=models.IntegerField(default=45, verbose_name='Срок изготовления (в днях)'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.TextField(blank=True, verbose_name='Материалы'),
        ),
    ]
