# Generated by Django 4.2.13 on 2024-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_dimensions_product_equipment_product_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.ImageField(blank=True, upload_to='static/product_images/design/', verbose_name='ЧБ эскиз'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/product/image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='static/product_images/image/', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='static/product_images/image/', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, upload_to='static/product_models/', verbose_name='3д модель'),
        ),
    ]
