# Generated by Django 4.2.13 on 2024-06-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_countertop_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='round_price',
            field=models.CharField(choices=[('home', 'Домой'), ('office', 'В офис'), ('kids', 'Детская')], default='home', max_length=10, verbose_name='Назначение'),
        ),
    ]
