# Generated by Django 4.2.13 on 2024-06-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_round_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='round_price',
            field=models.CharField(max_length=10, verbose_name='Круглая цена'),
        ),
    ]
